shared:
  image: node:20
  steps:
    - echo: echo hi
jobs:
  hub:
    requires: [~commit, ~pr]
  a:
    requires: []
  b:
    requires: [~a]
  c:
    requires: [~b]
  target:
    requires: [~stage@teardown_fail]
stages:
  teardown_fail:
    requires: [~hub]
    jobs: [a, b, c]
    description: First stage
    setup:
      image: node:20
      steps:
        - init: echo 'prod teardown'
    teardown:
      image: node:20
      steps:
        - sleep: sleep 15s
        - init: exit 1
