shared:
  image: node:20
  steps:
    - echo: echo hi
jobs:
  hub:
    requires: [~commit, ~pr]
    annotations:
      screwdriver.cd/virtualJob: true
  a:
    requires: []
  b:
    requires: [~a]
  c:
    requires: [~b]
  target:
    requires: [~stage@setup_fail]
    annotations:
      screwdriver.cd/virtualJob: true
stages:
  setup_fail:
    requires: [~hub]
    jobs: [a, b, c]
    description: First stage
    setup:
      image: node:20
      steps:
        - init: exit 1
    teardown:
      image: node:20
      steps:
        - init: echo 'prod teardown'
