shared:
  image: node:20
  steps:
    - echo: echo hi
jobs:
  hub:
    requires: [~commit, ~pr]
  a:
    requires: []
  b:
    requires: [~a]
  c:
    requires: []
  d:
    requires: [~c]
  target:
    requires: [~stage@simple_success2]
  join-target:
    requires: [stage@simple_success1, stage@simple_success2]
stages:
  simple_success1:
    requires: [~hub]
    jobs: [a, b]
    description: First stage
  simple_success2:
    requires: [~stage@simple_success1]
    jobs: [c, d]
    description: Second stage
