shared:
  image: node:20
  steps:
    - echo: echo hi
jobs:
  hub:
    requires: [~commit, ~pr]
    annotations:
      screwdriver.cd/virtualJob: true
  a:
    requires: []
  b:
    requires: [~a]
  c:
    requires: [~b]
    steps:
    - echo: exit 1;
  target:
    requires: [~stage@simple_fail]
    annotations:
      screwdriver.cd/virtualJob: true
stages:
  simple_fail:
    requires: [~hub]
    jobs: [a, b, c]
    description: First stage
